apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: tcp
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatfulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
      image: docker.io/confluentinc/cp-zookeeper:5.2.2
