apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
#  type: LoadBalancer
  ports:
  - name: client
    port: 2181
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: gcr.io/cit-262-fall/zookeeper
      ports:
      - name: client
        port: 2181
      - name: server
        port: 2888
      - name: leader-election
        port: 3888
      env:
      - name: ZOOKEEPER_CLIENT_PORT
        value: 2181
